GET http://127.0.0.1:8000/api/privelege/1 HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer 2|LrCs1StF4fJuW5ZHSWo7m5T3CIYyNfj6mdLlllfx


{
    "weapon_name": "new",
    "weapon_description": "new",
    "weapon_image": "new.png"
}
