PUT http://127.0.0.1/api/employee/update/1 HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer 10|IevDihaTjyk1L7CDuRKwBkWgM2hBDox2Ajis8Neh

{
   "first_name": "John",
    "middle_name": "Doe",
    "last_name": "Smith",
    "date_of_birth": "1990-01-01",
    "email": "john.smith@example.com",
    "phone": "1234567890",
    "password": "secret"
}