PUT http://127.0.0.1:8000/api/measurement/update/1 HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer 2|J6bkcrqQFPP4G0z4Kdh2cvs7I5Mk1PzGPRAp0vZW



{
    "measurement_name": "New Measurement",
    "measurement_description": "Description of the new measurement"
}
