
GET http://127.0.0.1:8000/api/backup/list HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer 1|pgAbAK2fEOmCSbxMuYMZ5PKr67MEvfhtDwCKk0pa9f2a732e
# Authorization: Bearer token
