PUT http://127.0.0.1:8000/api/process/create HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer your_access_token_here

{
    "role_name": "New Role",
    "role_description": "Role Description",
}