PUT http://127.0.0.1:8000/api/role/update/1 HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer 3|hdA7Ca7oFw33ysCf90X3RfTe1wGiXdaxPXxDMBP550d91f80


{
    "role_name": "New Role",
    "slug": "New Slug",
    "role_description": "Role Description"
}
