PUT http://127.0.0.1/api/gladiator/update/1 HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer 10|IevDihaTjyk1L7CDuRKwBkWgM2hBDox2Ajis8Neh


{
    "department_name": "New Department",
    "department_description": "Description of the new department",
    "parent_id": 3
}
