GET http://127.0.0.1:8000/api/department/assign-process HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer 1|sGsjH63GyxsFuhykkbR4qQ8oSadRkQGY1t14W82K050fc239

{
    "department_id": 1,
    "process_id": 1
}