PUT http://127.0.0.1/api/permission/update/1 HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer 9|HX3sFJfquM1dNMrB6YdIwEkmDkAuqwD38V9b7uPM


{
    "permission_name": "New Permission",
    "permission_description": "New Description",
}
