PUT http://127.0.0.1:8000/api/department/create HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer 4|HwvCVT8mHH0vPK9m5uTphfumdMi1VNM1qh8L0D77afd3bb34
# Authorization: Bearer token

{
    "department_name": "New Department",
    "department_description": "Description of the new department",
    "parent_id": 3
}


# # curl -X GET http://127.0.0.1:8000/api/employee \
# #     -H "Accept: application/json" \
# #     -H "Authorization: Bearer 3|dZmxl10u5o2vsVm83HDusekvtntGBlGzMxM0EKkp0379d8f0"


# Импортируем функцию для получения токена
# . _queries\auth\login.ps1

# # Получаем токен
# $token = Get-Token

# # Проверка, что токен был получен
# if (-not $token) {
#     Write-Error "Не удалось получить токен"
#     exit 1
# }

# # Выполнение запроса на создание сотрудника
# Invoke-RestMethod -Method Put -Uri "http://127.0.0.1:8000/api/employee/create" -Headers @{
#     "Accept"        = "application/json"
#     "Content-Type"  = "application/json"
#     "Authorization" = "Bearer $token"
# } -Body '{
#     "first_name": "John",
#     "middle_name": "Doe",
#     "last_name": "Smith",
#     "date_of_birth": "1990-01-01",
#     "email": "john.smith@example.com",
#     "phone": "1234567890",
#     "password": "secret_1"
# }'