PUT http://127.0.0.1:8000/api/department/add HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer your_access_token_here

{
    "department_name": "New Department",
    "department_description": "Description of the new department",
    "parent_id": null
}