PUT http://127.0.0.1:8000/api/employee/create HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer your_access_token_here

{
    "first_name": "John",
    "middle_name": "Doe",
    "last_name": "Smith",
    "date_of_birth": "1990-01-01",
    "email": "john.smith@example.com",
    "phone": "1234567890",
    "password": "secret"
}